name: test

on:
  push:
  pull_request:

jobs:
  test_linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          ca-certificates \
          imagemagick wget

      - name: check version
        run: convert --version

      - name: generate blue image
        run: |
          ./test.sh "top text" "smaller longer text describing whats going on. and also have some good motivation here." testfiles/screen_shot_android_02.png
          mv -v output.png output_blue.png

      - name: check output
        run: |
          ls -al output.png
          ls -hal output.png

